apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-10-94.ap-northeast-2.compute.internal

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-local-pvc
  namespace: kube-sample
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: local-storage


---
apiVersion: v1
kind: Service
metadata:
  name: web-localstorage
  namespace: kube-sample
spec:
  selector:
    app: web-localstorage
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30020
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-localstorage
  namespace: kube-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-localstorage
  template:
    metadata:
      labels:
        app: web-localstorage
    spec:
      containers:
      - name: web-localstorage
        image: nginx:1.21.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: local-vol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: local-vol
        persistentVolumeClaim:
          claimName: nginx-local-pvc